export const CHAMPIONS_TYPES = [
  'normal',
  'fire',
  'water',
  'electric',
  'grass',
  'ice',
  'fighting',
  'poison',
  'ground',
  'flying',
  'psychic',
  'bug',
  'rock',
  'ghost',
  'dragon',
  'dark',
  'steel',
  'fairy',
]

export const CHAMPIONS_NATURES = {
  adamant: ['atk', 'spa'],
  bashful: ['spa', 'spa'],
  bold: ['def', 'atk'],
  brave: ['atk', 'spe'],
  calm: ['spd', 'atk'],
  careful: ['spd', 'spa'],
  docile: ['def', 'def'],
  gentle: ['spd', 'def'],
  hardy: ['atk', 'atk'],
  hasty: ['spe', 'def'],
  impish: ['def', 'spa'],
  jolly: ['spe', 'spa'],
  lax: ['def', 'spd'],
  lonely: ['atk', 'def'],
  mild: ['spa', 'def'],
  modest: ['spa', 'atk'],
  naive: ['spe', 'spd'],
  naughty: ['atk', 'spd'],
  quiet: ['spa', 'spe'],
  quirky: ['spd', 'spd'],
  rash: ['spa', 'spd'],
  relaxed: ['def', 'spe'],
  sassy: ['spd', 'spe'],
  serious: ['spe', 'spe'],
  timid: ['spe', 'atk'],
}

export const CHAMPIONS_MOVES = {
  "acid-spray": {
    basePower: 40,
    category: "special",
    name: "Acid Spray",
    type: "poison",
  },
  "aerial-ace": {
    basePower: 60,
    category: "physical",
    name: "Aerial Ace",
    type: "flying",
  },
  "air-slash": {
    basePower: 75,
    category: "special",
    name: "Air Slash",
    type: "flying",
  },
  "alluring-voice": {
    basePower: 80,
    category: "special",
    name: "Alluring Voice",
    type: "fairy",
  },
  "aqua-cutter": {
    basePower: 70,
    category: "physical",
    name: "Aqua Cutter",
    type: "water",
  },
  "aqua-jet": {
    basePower: 40,
    category: "physical",
    name: "Aqua Jet",
    type: "water",
  },
  "aqua-step": {
    basePower: 80,
    category: "physical",
    name: "Aqua Step",
    type: "water",
  },
  "armor-cannon": {
    basePower: 120,
    category: "special",
    name: "Armor Cannon",
    type: "fire",
  },
  "aura-sphere": {
    basePower: 80,
    category: "special",
    name: "Aura Sphere",
    type: "fighting",
  },
  "bite": {
    basePower: 60,
    category: "physical",
    name: "Bite",
    type: "dark",
  },
  "bitter-blade": {
    basePower: 90,
    category: "physical",
    name: "Bitter Blade",
    type: "fire",
  },
  "blast-burn": {
    basePower: 150,
    category: "special",
    name: "Blast Burn",
    type: "fire",
  },
  "blizzard": {
    basePower: 110,
    category: "special",
    name: "Blizzard",
    target: "allAdjacentFoes",
    type: "ice",
  },
  "body-slam": {
    basePower: 85,
    category: "physical",
    name: "Body Slam",
    type: "normal",
  },
  "brave-bird": {
    basePower: 120,
    category: "physical",
    name: "Brave Bird",
    type: "flying",
  },
  "bug-bite": {
    basePower: 60,
    category: "physical",
    name: "Bug Bite",
    type: "bug",
  },
  "bug-buzz": {
    basePower: 90,
    category: "special",
    name: "Bug Buzz",
    type: "bug",
  },
  "bulldoze": {
    basePower: 60,
    category: "physical",
    name: "Bulldoze",
    target: "allAdjacent",
    type: "ground",
  },
  "bullet-punch": {
    basePower: 40,
    category: "physical",
    name: "Bullet Punch",
    type: "steel",
  },
  "ceaseless-edge": {
    basePower: 65,
    category: "physical",
    name: "Ceaseless Edge",
    type: "dark",
  },
  "chilling-water": {
    basePower: 50,
    category: "special",
    name: "Chilling Water",
    type: "water",
  },
  "close-combat": {
    basePower: 120,
    category: "physical",
    name: "Close Combat",
    type: "fighting",
  },
  "crunch": {
    basePower: 80,
    category: "physical",
    name: "Crunch",
    type: "dark",
  },
  "dark-pulse": {
    basePower: 80,
    category: "special",
    name: "Dark Pulse",
    type: "dark",
  },
  "dazzling-gleam": {
    basePower: 80,
    category: "special",
    name: "Dazzling Gleam",
    target: "allAdjacentFoes",
    type: "fairy",
  },
  "dire-claw": {
    basePower: 80,
    category: "physical",
    name: "Dire Claw",
    type: "poison",
  },
  "discharge": {
    basePower: 80,
    category: "special",
    name: "Discharge",
    target: "allAdjacent",
    type: "electric",
  },
  "double-edge": {
    basePower: 120,
    category: "physical",
    name: "Double-Edge",
    type: "normal",
  },
  "draco-meteor": {
    basePower: 130,
    category: "special",
    name: "Draco Meteor",
    type: "dragon",
  },
  "dragon-claw": {
    basePower: 80,
    category: "physical",
    name: "Dragon Claw",
    type: "dragon",
  },
  "dragon-pulse": {
    basePower: 85,
    category: "special",
    name: "Dragon Pulse",
    type: "dragon",
  },
  "dragon-tail": {
    basePower: 60,
    category: "physical",
    name: "Dragon Tail",
    type: "dragon",
  },
  "drain-punch": {
    basePower: 75,
    category: "physical",
    name: "Drain Punch",
    type: "fighting",
  },
  "draining-kiss": {
    basePower: 50,
    category: "special",
    name: "Draining Kiss",
    type: "fairy",
  },
  "drill-run": {
    basePower: 80,
    category: "physical",
    name: "Drill Run",
    type: "ground",
  },
  "dynamic-punch": {
    basePower: 100,
    category: "physical",
    name: "Dynamic Punch",
    type: "fighting",
  },
  "earth-power": {
    basePower: 90,
    category: "special",
    name: "Earth Power",
    type: "ground",
  },
  "earthquake": {
    basePower: 100,
    category: "physical",
    name: "Earthquake",
    target: "allAdjacent",
    type: "ground",
  },
  "energy-ball": {
    basePower: 90,
    category: "special",
    name: "Energy Ball",
    type: "grass",
  },
  "expanding-force": {
    basePower: 80,
    category: "special",
    name: "Expanding Force",
    type: "psychic",
  },
  "explosion": {
    basePower: 250,
    category: "physical",
    name: "Explosion",
    target: "allAdjacent",
    type: "normal",
  },
  "extreme-speed": {
    basePower: 80,
    category: "physical",
    name: "Extreme Speed",
    type: "normal",
  },
  "fake-out": {
    basePower: 40,
    category: "physical",
    name: "Fake Out",
    type: "normal",
  },
  "feint": {
    basePower: 30,
    category: "physical",
    name: "Feint",
    type: "normal",
  },
  "fell-stinger": {
    basePower: 50,
    category: "physical",
    name: "Fell Stinger",
    type: "bug",
  },
  "fiery-dance": {
    basePower: 80,
    category: "special",
    name: "Fiery Dance",
    type: "fire",
  },
  "fire-blast": {
    basePower: 110,
    category: "special",
    name: "Fire Blast",
    type: "fire",
  },
  "fire-punch": {
    basePower: 75,
    category: "physical",
    name: "Fire Punch",
    type: "fire",
  },
  "flame-charge": {
    basePower: 50,
    category: "physical",
    name: "Flame Charge",
    type: "fire",
  },
  "flamethrower": {
    basePower: 90,
    category: "special",
    name: "Flamethrower",
    type: "fire",
  },
  "flare-blitz": {
    basePower: 120,
    category: "physical",
    name: "Flare Blitz",
    type: "fire",
  },
  "flash-cannon": {
    basePower: 80,
    category: "special",
    name: "Flash Cannon",
    type: "steel",
  },
  "flip-turn": {
    basePower: 60,
    category: "physical",
    name: "Flip Turn",
    type: "water",
  },
  "focus-blast": {
    basePower: 120,
    category: "special",
    name: "Focus Blast",
    type: "fighting",
  },
  "giga-drain": {
    basePower: 75,
    category: "special",
    name: "Giga Drain",
    type: "grass",
  },
  "giga-impact": {
    basePower: 150,
    category: "physical",
    name: "Giga Impact",
    type: "normal",
  },
  "gigaton-hammer": {
    basePower: 160,
    category: "physical",
    name: "Gigaton Hammer",
    type: "steel",
  },
  "gunk-shot": {
    basePower: 120,
    category: "physical",
    name: "Gunk Shot",
    type: "poison",
  },
  "head-smash": {
    basePower: 150,
    category: "physical",
    name: "Head Smash",
    type: "rock",
  },
  "heat-wave": {
    basePower: 95,
    category: "special",
    name: "Heat Wave",
    target: "allAdjacentFoes",
    type: "fire",
  },
  "high-jump-kick": {
    basePower: 130,
    category: "physical",
    name: "High Jump Kick",
    type: "fighting",
  },
  "hurricane": {
    basePower: 110,
    category: "special",
    name: "Hurricane",
    type: "flying",
  },
  "hydro-cannon": {
    basePower: 150,
    category: "special",
    name: "Hydro Cannon",
    type: "water",
  },
  "hydro-pump": {
    basePower: 110,
    category: "special",
    name: "Hydro Pump",
    type: "water",
  },
  "hyper-beam": {
    basePower: 150,
    category: "special",
    name: "Hyper Beam",
    type: "normal",
  },
  "hyper-voice": {
    basePower: 90,
    category: "special",
    name: "Hyper Voice",
    target: "allAdjacentFoes",
    type: "normal",
  },
  "ice-beam": {
    basePower: 90,
    category: "special",
    name: "Ice Beam",
    type: "ice",
  },
  "ice-fang": {
    basePower: 65,
    category: "physical",
    name: "Ice Fang",
    type: "ice",
  },
  "ice-punch": {
    basePower: 75,
    category: "physical",
    name: "Ice Punch",
    type: "ice",
  },
  "ice-shard": {
    basePower: 40,
    category: "physical",
    name: "Ice Shard",
    type: "ice",
  },
  "ice-spinner": {
    basePower: 80,
    category: "physical",
    name: "Ice Spinner",
    type: "ice",
  },
  "icicle-crash": {
    basePower: 85,
    category: "physical",
    name: "Icicle Crash",
    type: "ice",
  },
  "icy-wind": {
    basePower: 55,
    category: "special",
    name: "Icy Wind",
    target: "allAdjacentFoes",
    type: "ice",
  },
  "infernal-parade": {
    basePower: 65,
    category: "special",
    name: "Infernal Parade",
    type: "ghost",
  },
  "iron-head": {
    basePower: 80,
    category: "physical",
    name: "Iron Head",
    type: "steel",
  },
  "iron-tail": {
    basePower: 100,
    category: "physical",
    name: "Iron Tail",
    type: "steel",
  },
  "jet-punch": {
    basePower: 60,
    category: "physical",
    name: "Jet Punch",
    type: "water",
  },
  "knock-off": {
    basePower: 65,
    category: "physical",
    name: "Knock Off",
    type: "dark",
  },
  "kowtow-cleave": {
    basePower: 85,
    category: "physical",
    name: "Kowtow Cleave",
    type: "dark",
  },
  "lava-plume": {
    basePower: 80,
    category: "special",
    name: "Lava Plume",
    target: "allAdjacent",
    type: "fire",
  },
  "leaf-blade": {
    basePower: 90,
    category: "physical",
    name: "Leaf Blade",
    type: "grass",
  },
  "leaf-storm": {
    basePower: 130,
    category: "special",
    name: "Leaf Storm",
    type: "grass",
  },
  "liquidation": {
    basePower: 85,
    category: "physical",
    name: "Liquidation",
    type: "water",
  },
  "lumina-crash": {
    basePower: 80,
    category: "special",
    name: "Lumina Crash",
    type: "psychic",
  },
  "matcha-gotcha": {
    basePower: 80,
    category: "special",
    name: "Matcha Gotcha",
    target: "allAdjacentFoes",
    type: "grass",
  },
  "megahorn": {
    basePower: 120,
    category: "physical",
    name: "Megahorn",
    type: "bug",
  },
  "meteor-mash": {
    basePower: 90,
    category: "physical",
    name: "Meteor Mash",
    type: "steel",
  },
  "moonblast": {
    basePower: 95,
    category: "special",
    name: "Moonblast",
    type: "fairy",
  },
  "mortal-spin": {
    basePower: 30,
    category: "physical",
    name: "Mortal Spin",
    target: "allAdjacentFoes",
    type: "poison",
  },
  "mud-shot": {
    basePower: 55,
    category: "special",
    name: "Mud Shot",
    type: "ground",
  },
  "mystical-fire": {
    basePower: 75,
    category: "special",
    name: "Mystical Fire",
    type: "fire",
  },
  "night-slash": {
    basePower: 70,
    category: "physical",
    name: "Night Slash",
    type: "dark",
  },
  "nuzzle": {
    basePower: 20,
    category: "physical",
    name: "Nuzzle",
    type: "electric",
  },
  "outrage": {
    basePower: 120,
    category: "physical",
    name: "Outrage",
    type: "dragon",
  },
  "overheat": {
    basePower: 130,
    category: "special",
    name: "Overheat",
    type: "fire",
  },
  "phantom-force": {
    basePower: 90,
    category: "physical",
    name: "Phantom Force",
    type: "ghost",
  },
  "play-rough": {
    basePower: 90,
    category: "physical",
    name: "Play Rough",
    type: "fairy",
  },
  "poison-jab": {
    basePower: 80,
    category: "physical",
    name: "Poison Jab",
    type: "poison",
  },
  "poltergeist": {
    basePower: 110,
    category: "physical",
    name: "Poltergeist",
    type: "ghost",
  },
  "power-gem": {
    basePower: 80,
    category: "special",
    name: "Power Gem",
    type: "rock",
  },
  "power-whip": {
    basePower: 120,
    category: "physical",
    name: "Power Whip",
    type: "grass",
  },
  "psychic": {
    basePower: 90,
    category: "special",
    name: "Psychic",
    type: "psychic",
  },
  "psychic-fangs": {
    basePower: 85,
    category: "physical",
    name: "Psychic Fangs",
    type: "psychic",
  },
  "psychic-noise": {
    basePower: 75,
    category: "special",
    name: "Psychic Noise",
    type: "psychic",
  },
  "raging-bull": {
    basePower: 90,
    category: "physical",
    name: "Raging Bull",
    type: "normal",
  },
  "raging-fury": {
    basePower: 120,
    category: "physical",
    name: "Raging Fury",
    type: "fire",
  },
  "rapid-spin": {
    basePower: 50,
    category: "physical",
    name: "Rapid Spin",
    type: "normal",
  },
  "razor-shell": {
    basePower: 75,
    category: "physical",
    name: "Razor Shell",
    type: "water",
  },
  "rock-slide": {
    basePower: 75,
    category: "physical",
    name: "Rock Slide",
    target: "allAdjacentFoes",
    type: "rock",
  },
  "rock-tomb": {
    basePower: 60,
    category: "physical",
    name: "Rock Tomb",
    type: "rock",
  },
  "salt-cure": {
    basePower: 40,
    category: "physical",
    name: "Salt Cure",
    type: "rock",
  },
  "scald": {
    basePower: 80,
    category: "special",
    name: "Scald",
    type: "water",
  },
  "seed-bomb": {
    basePower: 80,
    category: "physical",
    name: "Seed Bomb",
    type: "grass",
  },
  "shadow-ball": {
    basePower: 80,
    category: "special",
    name: "Shadow Ball",
    type: "ghost",
  },
  "shadow-claw": {
    basePower: 70,
    category: "physical",
    name: "Shadow Claw",
    type: "ghost",
  },
  "shadow-punch": {
    basePower: 60,
    category: "physical",
    name: "Shadow Punch",
    type: "ghost",
  },
  "shadow-sneak": {
    basePower: 40,
    category: "physical",
    name: "Shadow Sneak",
    type: "ghost",
  },
  "sludge-bomb": {
    basePower: 90,
    category: "special",
    name: "Sludge Bomb",
    type: "poison",
  },
  "sludge-wave": {
    basePower: 95,
    category: "special",
    name: "Sludge Wave",
    target: "allAdjacent",
    type: "poison",
  },
  "snarl": {
    basePower: 55,
    category: "special",
    name: "Snarl",
    target: "allAdjacentFoes",
    type: "dark",
  },
  "solar-beam": {
    basePower: 120,
    category: "special",
    name: "Solar Beam",
    type: "grass",
  },
  "spirit-shackle": {
    basePower: 90,
    category: "physical",
    name: "Spirit Shackle",
    type: "ghost",
  },
  "stone-axe": {
    basePower: 65,
    category: "physical",
    name: "Stone Axe",
    type: "rock",
  },
  "stone-edge": {
    basePower: 100,
    category: "physical",
    name: "Stone Edge",
    type: "rock",
  },
  "struggle-bug": {
    basePower: 50,
    category: "special",
    name: "Struggle Bug",
    target: "allAdjacentFoes",
    type: "bug",
  },
  "sucker-punch": {
    basePower: 70,
    category: "physical",
    name: "Sucker Punch",
    type: "dark",
  },
  "superpower": {
    basePower: 120,
    category: "physical",
    name: "Superpower",
    type: "fighting",
  },
  "surf": {
    basePower: 90,
    category: "special",
    name: "Surf",
    target: "allAdjacent",
    type: "water",
  },
  "syrup-bomb": {
    basePower: 60,
    category: "special",
    name: "Syrup Bomb",
    type: "grass",
  },
  "throat-chop": {
    basePower: 80,
    category: "physical",
    name: "Throat Chop",
    type: "dark",
  },
  "thunder": {
    basePower: 110,
    category: "special",
    name: "Thunder",
    type: "electric",
  },
  "thunderbolt": {
    basePower: 90,
    category: "special",
    name: "Thunderbolt",
    type: "electric",
  },
  "torch-song": {
    basePower: 80,
    category: "special",
    name: "Torch Song",
    type: "fire",
  },
  "trailblaze": {
    basePower: 50,
    category: "physical",
    name: "Trailblaze",
    type: "grass",
  },
  "triple-arrows": {
    basePower: 90,
    category: "physical",
    name: "Triple Arrows",
    type: "fighting",
  },
  "u-turn": {
    basePower: 70,
    category: "physical",
    name: "U-turn",
    type: "bug",
  },
  "vacuum-wave": {
    basePower: 40,
    category: "special",
    name: "Vacuum Wave",
    type: "fighting",
  },
  "volt-switch": {
    basePower: 70,
    category: "special",
    name: "Volt Switch",
    type: "electric",
  },
  "water-pulse": {
    basePower: 60,
    category: "special",
    name: "Water Pulse",
    type: "water",
  },
  "waterfall": {
    basePower: 80,
    category: "physical",
    name: "Waterfall",
    type: "water",
  },
  "wave-crash": {
    basePower: 120,
    category: "physical",
    name: "Wave Crash",
    type: "water",
  },
  "whirlpool": {
    basePower: 35,
    category: "special",
    name: "Whirlpool",
    type: "water",
  },
  "wild-charge": {
    basePower: 90,
    category: "physical",
    name: "Wild Charge",
    type: "electric",
  },
  "wood-hammer": {
    basePower: 120,
    category: "physical",
    name: "Wood Hammer",
    type: "grass",
  },
  "x-scissor": {
    basePower: 80,
    category: "physical",
    name: "X-Scissor",
    type: "bug",
  },
  "zen-headbutt": {
    basePower: 80,
    category: "physical",
    name: "Zen Headbutt",
    type: "psychic",
  },
}

export const CHAMPIONS_TYPE_CHART = {
  normal: {
    rock: 0.5,
    ghost: 0,
    steel: 0.5,
  },
  fire: {
    fire: 0.5,
    water: 0.5,
    grass: 2,
    ice: 2,
    bug: 2,
    rock: 0.5,
    dragon: 0.5,
    steel: 2,
  },
  water: {
    fire: 2,
    water: 0.5,
    grass: 0.5,
    ground: 2,
    rock: 2,
    dragon: 0.5,
  },
  electric: {
    water: 2,
    electric: 0.5,
    grass: 0.5,
    ground: 0,
    flying: 2,
    dragon: 0.5,
  },
  grass: {
    fire: 0.5,
    water: 2,
    grass: 0.5,
    poison: 0.5,
    ground: 2,
    flying: 0.5,
    bug: 0.5,
    rock: 2,
    dragon: 0.5,
    steel: 0.5,
  },
  ice: {
    fire: 0.5,
    water: 0.5,
    grass: 2,
    ice: 0.5,
    ground: 2,
    flying: 2,
    dragon: 2,
    steel: 0.5,
  },
  fighting: {
    normal: 2,
    ice: 2,
    poison: 0.5,
    flying: 0.5,
    psychic: 0.5,
    bug: 0.5,
    rock: 2,
    ghost: 0,
    dark: 2,
    steel: 2,
    fairy: 0.5,
  },
  poison: {
    grass: 2,
    poison: 0.5,
    ground: 0.5,
    rock: 0.5,
    ghost: 0.5,
    steel: 0,
    fairy: 2,
  },
  ground: {
    fire: 2,
    electric: 2,
    grass: 0.5,
    poison: 2,
    flying: 0,
    bug: 0.5,
    rock: 2,
    steel: 2,
  },
  flying: {
    electric: 0.5,
    grass: 2,
    fighting: 2,
    bug: 2,
    rock: 0.5,
    steel: 0.5,
  },
  psychic: {
    fighting: 2,
    poison: 2,
    psychic: 0.5,
    dark: 0,
    steel: 0.5,
  },
  bug: {
    fire: 0.5,
    grass: 2,
    fighting: 0.5,
    poison: 0.5,
    flying: 0.5,
    psychic: 2,
    ghost: 0.5,
    dark: 2,
    steel: 0.5,
    fairy: 0.5,
  },
  rock: {
    fire: 2,
    ice: 2,
    fighting: 0.5,
    ground: 0.5,
    flying: 2,
    bug: 2,
    steel: 0.5,
  },
  ghost: {
    normal: 0,
    psychic: 2,
    ghost: 2,
    dark: 0.5,
  },
  dragon: {
    dragon: 2,
    steel: 0.5,
    fairy: 0,
  },
  dark: {
    fighting: 0.5,
    psychic: 2,
    ghost: 2,
    dark: 0.5,
    fairy: 0.5,
  },
  steel: {
    fire: 0.5,
    water: 0.5,
    electric: 0.5,
    ice: 2,
    rock: 2,
    steel: 0.5,
    fairy: 2,
  },
  fairy: {
    fire: 0.5,
    fighting: 2,
    poison: 0.5,
    dragon: 2,
    dark: 2,
    steel: 0.5,
  },
}
